### ISSUE TITLE
SEV2.5 GAMBLING DOWN

### ISSUE THREAD

**Issue by DonutsInBelly** [dominusbelli/twitchbot#2]
Impacted
- !points
- !gamble

2 Customers impacted

Mitigation
Since feature is not crititcal to function of stream, this can be handled after stream.
Fix will be deployed tomorrow when streamer has time to fix.

**Comment by Sail338** [comment]
Will there be a COE?

**Comment by DonutsInBelly** [comment]
I don't see any +1s so no

**Comment by DonutsInBelly** [comment]
Issue is mitigated as commands work after a new deployment
reducing to SEV3


Issue cannot be closed as an error appears on almost every command
```
TypeError: Cannot read property 'response' of null
```
